import "./styles.css";

const DATA_ROOT = "/data/cornell";
const categories = {
  communities: { label: "Communities", icon: "◌", description: "Find people and places where your interests have a home." },
  people: { label: "People", icon: "◎", description: "Discover Cornellians, networks, mentors, and paths to connection." },
  events: { label: "Events", icon: "◷", description: "See what is happening across Cornell and its communities." },
  opportunities: { label: "Opportunities", icon: "↗", description: "Find a next step: research, programs, funding, and more." },
  entrepreneurship: { label: "Entrepreneurship", icon: "✦", description: "Explore the people, programs, spaces, and ideas behind Cornell ventures." },
  student_built: { label: "Student-built", icon: "⌘", description: "Surface the tools and resources students make for each other." },
};
const interestOptions = [
  ["entrepreneurship", "Entrepreneurship"], ["artificial-intelligence", "AI / Technology"], ["sustainability", "Sustainability"],
  ["emerging-markets", "Emerging Markets"], ["research", "Research"], ["global", "Global / International"],
  ["startups", "Startups / Venture"], ["career", "Career"], ["student-built", "Student-built tools"],
];
const synonyms = { founder: ["founders", "startup", "startups", "entrepreneurship", "entrepreneurs"], founders: ["founder", "startup", "startups", "entrepreneurship", "entrepreneurs"], startup: ["startups", "founder", "founders", "entrepreneurship", "venture"], ai: ["artificial intelligence", "generative ai", "technology"], climate: ["sustainability", "green technology", "emerging markets"], international: ["emerging markets", "global", "alumni"], club: ["community", "student organization", "student club"], help: ["support", "career", "research", "mentorship"] };
const stopWords = new Set(["a", "an", "and", "around", "about", "are", "can", "do", "for", "from", "how", "i", "in", "is", "it", "me", "my", "of", "on", "or", "show", "something", "that", "the", "this", "to", "want", "what", "where", "with", "you"]);
const state = { entities: [], relationships: [], route: { page: "home" } };

const escapeHtml = (value = "") => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const slugLabel = (value = "") => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const normalize = (value = "") => value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const tokenize = (value = "") => normalize(value).split(/\s+/).filter((token) => token.length > 1 && !stopWords.has(token));
const sourceLabel = (type = "") => ({ official_university: "Official Cornell", official_school_department: "Johnson", cornellian_community: "Cornellian", student_built: "Student-built", external: "External" }[type] || slugLabel(type));

function memory() { try { return JSON.parse(localStorage.getItem("student-os-memory") || "{}") || {}; } catch { return {}; } }
function updateMemory(update) { try { localStorage.setItem("student-os-memory", JSON.stringify({ ...memory(), ...update })); } catch { /* local session is optional */ } }
function getProfile() { return { university: "Cornell University", school: "", program: "", year: "", interests: [], ...(memory().profile || {}) }; }
function hasProfileContext() { const profile = getProfile(); return Boolean(profile.interests?.length || profile.program || profile.year); }
function rememberEntity(id) { const current = memory(); const entity = getEntityById(id); const records = (current.viewedEntities || []).filter((item) => item.id !== id); updateMemory({ viewedEntityIds: [id, ...(current.viewedEntityIds || []).filter((item) => item !== id)].slice(0, 12), viewedEntities: [{ id, category: entity?.domains?.[0] || "", viewedAt: new Date().toISOString() }, ...records].slice(0, 8) }); }
function rememberCategory(category) { const current = memory(); updateMemory({ selectedCategories: [category, ...(current.selectedCategories || []).filter((item) => item !== category)].slice(0, 6) }); }
function rememberQuery(query) { const current = memory(); updateMemory({ recentQueries: [query, ...(current.recentQueries || []).filter((item) => item !== query)].slice(0, 6) }); }
function isSaved(id) { return (memory().savedEntityIds || []).includes(id); }
function toggleSaved(id) { const current = memory(); const saved = current.savedEntityIds || []; updateMemory({ savedEntityIds: saved.includes(id) ? saved.filter((item) => item !== id) : [id, ...saved] }); }
function viewedEntities() { const current = memory(); const ids = current.viewedEntities?.map((item) => item.id) || current.viewedEntityIds || []; return [...new Set(ids)].map(getEntityById).filter(Boolean); }
function savedEntities() { return (memory().savedEntityIds || []).map(getEntityById).filter(Boolean); }

function getEntitiesByCategory(category) { return state.entities.filter((entity) => entity.domains?.includes(category)); }
function getEntityById(id) { return state.entities.find((entity) => entity.id === id); }
function getRelatedEntities(entityId) { const linkedIds = state.relationships.filter((item) => item.fromEntityId === entityId || item.toEntityId === entityId).map((item) => item.fromEntityId === entityId ? item.toEntityId : item.fromEntityId); return [...new Set(linkedIds)].map(getEntityById).filter(Boolean); }
function getRelationship(entityId, relatedId) { return state.relationships.find((item) => (item.fromEntityId === entityId && item.toEntityId === relatedId) || (item.toEntityId === entityId && item.fromEntityId === relatedId)); }
function getRelationshipLabel(entityId, relatedId) { const relationship = getRelationship(entityId, relatedId); return relationship ? relationship.type.replaceAll("_", " ") : "related"; }
function iconForEntity(entity) { return categories[entity.domains?.[0]]?.icon || "•"; }
function entitySearchText(entity) { const relatedNames = getRelatedEntities(entity.id).map((item) => item.name).join(" "); return normalize([entity.name, entity.kind, entity.shortDescription, ...(entity.domains || []), ...(entity.tags || []), ...(entity.interests || []), entity.program, entity.school, entity.department, entity.audience?.audiences?.join(" "), entity.audience?.programs?.join(" "), relatedNames].filter(Boolean).join(" ")); }

function profileTokens() { const profile = getProfile(); return [...(profile.interests || []), profile.program, profile.school, profile.year].filter(Boolean).flatMap((item) => tokenize(item)); }
function profileRelevance(entity) { const tokens = profileTokens(); if (!tokens.length) return 0; const text = entitySearchText(entity); return tokens.reduce((score, token) => score + (text.includes(token) ? 4 : 0), 0); }
function interpretQuery(query) { const normalized = normalize(query); const tokens = tokenize(query); return { category: Object.keys(categories).find((category) => normalized.includes(category.replaceAll("_", " ")) || (category === "communities" && /(club|community|people like)/.test(normalized)) || (category === "events" && /(event|happening|this week|tonight)/.test(normalized)) || (category === "opportunities" && /(opportunit|fellowship|competition|funding|research)/.test(normalized))) || null, discovery: /(don t know|didn t know|interesting|surprising|new|discover)/.test(normalized), terms: [...tokens, ...tokens.flatMap((token) => synonyms[token] || [])] }; }
function searchEntities(query) {
  const intent = interpretQuery(query); const normalizedQuery = normalize(query); const current = memory();
  const scored = state.entities.map((entity) => { const text = entitySearchText(entity); let score = 0; let queryMatch = false; if (normalize(entity.name) === normalizedQuery) { score += 24; queryMatch = true; } if (normalize(entity.name).includes(normalizedQuery) && normalizedQuery.length > 2) { score += 15; queryMatch = true; } for (const term of intent.terms) { if (normalize(entity.name).includes(term)) { score += 12; queryMatch = true; } if ((entity.tags || []).some((tag) => normalize(tag).includes(term))) { score += 12; queryMatch = true; } if (text.includes(term)) { score += 2; queryMatch = true; } } if (intent.category && entity.domains?.includes(intent.category)) { score += 8; queryMatch = true; } if (queryMatch) score += Math.min(profileRelevance(entity), 4); if (entity.source?.sourceType === "student_built" && intent.discovery) score += 3; if (current.viewedEntityIds?.includes(entity.id)) score += 1; return { entity, score }; }).filter((item) => item.score > 2).sort((a, b) => b.score - a.score);
  return { intent, results: scored.slice(0, 12).map((item) => item.entity) };
}

function discoverEntities() {
  const current = memory(); const profile = getProfile(); const viewed = new Set(current.viewedEntityIds || []); const selected = new Set(current.selectedCategories || []); const anchors = [...(current.viewedEntityIds || [])].map(getEntityById).filter(Boolean); const candidates = state.entities.filter((entity) => !viewed.has(entity.id));
  const scored = candidates.map((entity) => { let score = profileRelevance(entity); const relatedToAnchor = anchors.filter((anchor) => getRelatedEntities(anchor.id).some((item) => item.id === entity.id)); score += relatedToAnchor.length * 12; if (entity.domains?.some((domain) => selected.has(domain))) score += 5; if (entity.domains?.some((domain) => profile.interests?.some((interest) => normalize(interest).includes(normalize(domain))))) score += 5; if (entity.source?.sourceType === "student_built") score += 4; if (entity.domains?.some((domain) => ["people", "events", "student_built"].includes(domain))) score += 3; return { entity, score, relatedToAnchor }; }).sort((a, b) => b.score - a.score);
  const picks = []; const domains = new Set(); for (const item of scored) { const domain = item.entity.domains?.find((candidate) => ["people", "events", "student_built", "opportunities", "communities", "entrepreneurship"].includes(candidate)); if (domain && (!domains.has(domain) || picks.length < 2) && item.score > 0) { picks.push(item); domains.add(domain); } if (picks.length === 5) break; }
  if (!picks.length) return state.entities.filter((entity) => ["big-red-ai", "jct-mba-course-planner", "ccem", "life-changing-labs"].includes(entity.id)).map((entity) => ({ entity, score: 0, relatedToAnchor: [] })); return picks;
}
function discoveryReason(item) { const current = memory(); const profile = getProfile(); if (item.relatedToAnchor[0]) return `Related to ${item.relatedToAnchor[0].name}`; if (item.entity.source?.sourceType === "student_built") return "Student-built resource in the Cornell ecosystem"; if (profile.interests?.length && profileRelevance(item.entity) > 0) return `Because you're interested in ${profile.interests[0]}`; if (current.selectedCategories?.length && item.entity.domains?.some((domain) => current.selectedCategories.includes(domain))) return `Because you explored ${categories[current.selectedCategories[0]]?.label || "this area"}`; if (item.entity.domains?.includes("people")) return "A people-discovery path in the current dataset"; if (item.entity.domains?.includes("events")) return "A way into Cornell's active communities"; return "A useful place to start exploring Cornell"; }

function journeyIntent(query) {
  const normalized = normalize(query);
  if (/(don t know|didn t know|interesting|surprising|something new|discover)/.test(normalized)) return { key: "discovery", label: "a new corner of Cornell", stages: ["communities", "people", "entrepreneurship", "events", "opportunities", "student_built"] };
  if (/(ai|artificial intelligence|technology|tech)/.test(normalized)) return { key: "ai", label: "AI and technology", stages: ["communities", "people", "entrepreneurship", "events", "opportunities", "student_built"] };
  if (/(founder|founders|meet people)/.test(normalized)) return { key: "people", label: "Cornell founders and people", stages: ["people", "communities", "entrepreneurship", "events", "opportunities"] };
  if (/(community|club|student group)/.test(normalized) && /(startup|venture|entrepreneur)/.test(normalized)) return { key: "community", label: "a startup community", stages: ["communities", "people", "entrepreneurship", "events", "opportunities", "student_built"] };
  if (/(entrepreneur|startup|venture|pitch)/.test(normalized)) return { key: "entrepreneurship", label: "entrepreneurship at Cornell", stages: ["entrepreneurship", "people", "communities", "events", "opportunities", "student_built"] };
  return null;
}
function journeyReason(stage, fromEntity, intent) {
  const labels = { start: "Best starting point for your interest.", people: "Meet people in this ecosystem.", communities: "Find a community connected to this path.", entrepreneurship: "A place to build or explore the idea.", events: "A way to connect with this ecosystem in action.", opportunities: "A next step after exploring this path.", student_built: "A student-built resource worth discovering." };
  return fromEntity ? `${labels[stage] || "Connected to the path."} Linked from ${fromEntity.name}.` : (labels[stage] || `A relevant part of ${intent.label}.`);
}
function journeyMatches(entity, intent) { return intent.key === "discovery" ? 1 : [...intent.label.split(" "), ...(entity.tags || [])].reduce((score, token) => entitySearchText(entity).includes(normalize(token)) ? score + 1 : score, 0); }
function buildJourney(query) {
  const intent = journeyIntent(query); if (!intent) return null;
  const search = searchEntities(query); const preferred = intent.key === "discovery" ? null : search.results.find((entity) => entity.domains?.some((domain) => intent.stages.includes(domain)));
  const fallbackIds = { entrepreneurship: "entrepreneurship-at-cornell", ai: "big-red-ai", people: "big-red-ai", community: "gorges-ventures", discovery: "entrepreneurship-at-cornell" };
  const start = preferred || getEntityById(fallbackIds[intent.key]); if (!start) return null;
  const steps = [{ stage: "start", entity: start, from: null }]; const used = new Set([start.id]);
  for (const stage of intent.stages) {
    if (stage === "start") continue;
    const candidates = state.entities.filter((entity) => !used.has(entity.id) && entity.domains?.includes(stage)).map((entity) => {
      const from = steps.map((step) => step.entity).find((previous) => getRelatedEntities(previous.id).some((related) => related.id === entity.id));
      return { entity, from, score: (from ? 20 : 0) + journeyMatches(entity, intent) + (entity.source?.sourceType === "student_built" ? 3 : 0) };
    }).filter((item) => item.from).sort((a, b) => b.score - a.score);
    if (candidates[0]) { used.add(candidates[0].entity.id); steps.push({ stage, entity: candidates[0].entity, from: candidates[0].from }); }
    if (steps.length >= 5) break;
  }
  const unexpected = state.entities.filter((entity) => !used.has(entity.id) && entity.source?.sourceType === "student_built").map((entity) => ({ entity, from: steps.find((step) => getRelatedEntities(step.entity.id).some((related) => related.id === entity.id))?.entity, score: journeyMatches(entity, intent) })).sort((a, b) => (b.from ? 10 : 0) + b.score - ((a.from ? 10 : 0) + a.score))[0];
  return { intent, query, steps, unexpected: unexpected || null };
}
function journeySaved(journey) { return journey.steps.every((step) => isSaved(step.entity.id)); }
function journeyView(journey, compact = false) {
  if (!journey?.steps?.length) return "";
  return `<section class="journey ${compact ? "journey--compact" : ""}"><div class="journey-heading"><div><span class="section-kicker section-kicker--spark">Connected journey</span><h2>${compact ? "Continue exploring" : `Explore ${escapeHtml(journey.intent.label)}`}</h2><p>${compact ? "A few connected next steps from what you just explored." : "A verified path through Cornell's connected ecosystem."}</p></div><button class="journey-save" data-save-journey="${escapeHtml(journey.steps.map((step) => step.entity.id).join(","))}">${journeySaved(journey) ? "Journey saved" : "Save this journey"}</button></div><div class="journey-path">${journey.steps.map((step, index) => `<div class="journey-step"><div class="journey-node"><span>${index + 1}</span></div><div class="journey-card"><div class="journey-card__stage">${escapeHtml(step.stage === "start" ? "Start" : categories[step.stage]?.label || slugLabel(step.stage))}</div>${entityCard(step.entity, { compact: true })}<p class="journey-card__reason">${escapeHtml(journeyReason(step.stage, step.from, journey.intent))}</p></div></div>`).join("")}</div>${journey.unexpected ? `<div class="journey-discovery"><span class="journey-discovery__mark">✦</span><div><span class="section-kicker section-kicker--spark">One more thing you might not know</span><button class="journey-discovery__link" data-entity-id="${escapeHtml(journey.unexpected.entity.id)}">${escapeHtml(journey.unexpected.entity.name)} ↗</button><p>${escapeHtml(journey.unexpected.from ? `Related to ${journey.unexpected.from.name}. ${journey.unexpected.entity.shortDescription}` : `Outside this path, this student-built resource is worth a look. ${journey.unexpected.entity.shortDescription}`)}</p></div></div>` : ""}<div class="journey-next"><span class="section-kicker">What's next?</span><p>${escapeHtml(journey.steps[journey.steps.length - 1].entity.name)} is the next place to continue.</p><button class="primary-action" data-entity-id="${escapeHtml(journey.steps[journey.steps.length - 1].entity.id)}">Explore next <span>↗</span></button></div></section>`;
}

function entityCard(entity, options = {}) { const metadata = [entity.audience?.programs?.[0], entity.program, entity.date?.startAt].filter(Boolean); return `<article class="entity-card ${options.compact ? "entity-card--compact" : ""}" data-entity-id="${escapeHtml(entity.id)}" tabindex="0" role="button" aria-label="Open ${escapeHtml(entity.name)}"><div class="entity-card__topline"><span class="entity-icon">${iconForEntity(entity)}</span><span class="eyebrow">${escapeHtml(slugLabel(entity.kind))}</span><span class="source-badge source-badge--${escapeHtml(entity.source.sourceType)}">${escapeHtml(sourceLabel(entity.source.sourceType))}</span></div><h3>${escapeHtml(entity.name)}</h3><p>${escapeHtml(entity.shortDescription)}</p><div class="entity-card__bottom"><div class="tag-row">${(entity.tags || []).slice(0, 2).map((tag) => `<span class="tag">${escapeHtml(tag.replaceAll("-", " "))}</span>`).join("")}</div><button class="card-save ${isSaved(entity.id) ? "card-save--saved" : ""}" data-save-id="${escapeHtml(entity.id)}" aria-label="${isSaved(entity.id) ? "Remove from saved" : "Save"}">${isSaved(entity.id) ? "★" : "☆"}</button><span class="arrow">↗</span></div>${metadata.length ? `<div class="card-meta">${escapeHtml(metadata.join(" · "))}</div>` : ""}</article>`; }
function categoryCard(category) { const count = getEntitiesByCategory(category).length; const relevant = getEntitiesByCategory(category).filter((entity) => profileRelevance(entity) > 0).length; const details = categories[category]; return `<button class="category-card" data-category="${category}"><span class="category-card__icon">${details.icon}</span><span class="category-card__label">${details.label}</span><span class="category-card__description">${details.description}</span><span class="category-card__footer"><strong>${relevant && relevant < count ? `${relevant} relevant` : `${count} resources`}</strong><span>Explore ↗</span></span></button>`; }
function promptChips() { return `<div class="prompt-row"><button data-ask-query="I'm interested in entrepreneurship but don't know where to start.">I'm curious about entrepreneurship</button><button data-ask-query="Find communities for me.">Find a community</button><button data-ask-query="What events are happening?"><span>What's happening?</span></button></div>`; }
function appShell(content) { const profile = getProfile(); const title = hasProfileContext() ? "My Cornell OS" : "Student OS"; return `<div class="app-shell"><header class="topbar"><button class="brand" data-route="home" aria-label="Go to Student OS home"><span class="brand-mark">so</span><span>${title}</span></button><div class="university-pill"><span class="cornell-dot"></span><span>Cornell University</span></div><nav class="topnav" aria-label="Primary navigation"><button data-route="home" class="topnav__link">Home</button><button data-route="explore" class="topnav__link">Explore</button><button data-route="discover" class="topnav__link">Discover</button><button data-route="saved" class="topnav__link">Saved</button></nav><button class="profile-chip" data-route="profile" aria-label="Open profile settings"><span class="profile-avatar">${profile.interests?.length ? "✦" : "P"}</span><span class="profile-name">${profile.program || "Your profile"}</span></button></header><main>${content}</main><footer class="footer"><span>Student OS · Cornell</span><span>Explore what your university has to offer.</span></footer></div>`; }
function askBar(value = "") { return `<form class="ask-bar" id="ask-form"><span>⌕</span><input id="ask-input" aria-label="What are you looking for?" placeholder="What are you looking for?" value="${escapeHtml(value)}" /><button type="submit">Ask Student OS <span>↗</span></button></form>`; }
function onboardingModal() { const profile = getProfile(); return `<div class="modal-backdrop"><section class="onboarding-modal" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div class="modal-kicker">Make it yours</div><h2 id="onboarding-title">What are you curious about?</h2><p>Pick a few interests and we'll make your Cornell OS feel more like yours. You can skip or change this later.</p><form id="onboarding-form"><div class="interest-grid">${interestOptions.map(([value, label]) => `<label class="interest-option"><input type="checkbox" name="interest" value="${value}" ${profile.interests?.includes(value) ? "checked" : ""} /><span>${label}</span></label>`).join("")}</div><div class="profile-fields"><label>School<select name="school"><option value="">Skip for now</option><option value="Johnson School of Management">Johnson School of Management</option></select></label><label>Program<select name="program"><option value="">Skip for now</option><option value="MBA">MBA</option></select></label><label>Year<select name="year"><option value="">Skip for now</option><option value="Year 1">Year 1</option><option value="Year 2">Year 2</option></select></label></div><div class="modal-actions"><button type="button" class="text-action" data-skip-onboarding>Skip for now</button><button type="submit" class="primary-action">Build my OS <span>↗</span></button></div></form></section></div>`; }

function homeView() { const discoveries = discoverEntities(); const recent = viewedEntities().slice(0, 4); const profile = getProfile(); const shouldOnboard = !memory().onboardingComplete; return appShell(`<section class="hero page-width"><div class="hero__copy"><div class="kicker"><span class="kicker-dot"></span> Cornell University · your discovery layer</div><h1>${hasProfileContext() ? "Your Cornell ecosystem, made more relevant." : "Your university has <em>more</em> to offer than you know."}</h1><p class="hero__lead">Student OS brings Cornell's communities, people, events, opportunities, entrepreneurship, and student-built resources into one discoverable experience.</p></div><div class="search-card"><div class="search-card__label">Ask your university</div>${askBar()}<div class="ask-examples">Try a question or a direction</div>${promptChips()}</div></section>${hasProfileContext() ? `<section class="personal-context page-width"><span class="section-kicker">For you</span><p>${escapeHtml([profile.program, ...(profile.interests || []).slice(0, 3)].filter(Boolean).join(" · "))}</p><button data-route="profile">Edit your context ↗</button></section>` : ""}<section class="section page-width"><div class="section-heading"><div><span class="section-kicker">Explore</span><h2>Find your way into Cornell.</h2></div><p>Six lenses into one connected ecosystem.</p></div><div class="category-grid">${Object.keys(categories).map(categoryCard).join("")}</div></section><section class="section section--discover page-width"><div class="section-heading"><div><span class="section-kicker section-kicker--spark">For you</span><h2>✨ You might not know these exist</h2></div><p>${recent.length || hasProfileContext() ? "Relevant, with a little surprise." : "Start exploring and we'll personalize your OS."}</p></div><div class="entity-grid entity-grid--four">${discoveries.map((item) => `<div class="discovery-item">${entityCard(item.entity)}<div class="discovery-reason">${escapeHtml(discoveryReason(item))}</div></div>`).join("")}</div></section>${recent.length ? `<section class="section page-width recent-section"><div class="section-heading"><div><span class="section-kicker">Your trail</span><h2>Recently explored</h2></div></div><div class="entity-grid entity-grid--four">${recent.map((entity) => entityCard(entity, { compact: true })).join("")}</div></section>` : ""}${shouldOnboard ? onboardingModal() : ""}`); }

function exploreView(category = null) { if (!category || !categories[category]) return appShell(`<section class="page-width page-intro"><span class="section-kicker">Explore</span><h1>Find your way into Cornell.</h1><p>Browse by the kind of connection you want to make.</p><div class="category-grid category-grid--explore">${Object.keys(categories).map(categoryCard).join("")}</div></section>`); rememberCategory(category); const details = categories[category]; const entities = getEntitiesByCategory(category).sort((a, b) => profileRelevance(b) - profileRelevance(a)); return appShell(`<section class="page-width category-hero"><button class="back-link" data-route="explore">← All areas</button><div class="category-hero__row"><div><span class="category-hero__icon">${details.icon}</span><span class="section-kicker">Explore area</span><h1>${details.label}</h1><p>${details.description}</p></div><div class="category-count"><strong>${entities.length}</strong><span>resources to explore</span></div></div></section><section class="page-width category-results"><div class="results-toolbar"><div><span class="section-kicker">${entities.length} results</span><h2>Explore ${details.label.toLowerCase()}</h2></div><label class="mini-search"><span>⌕</span><input id="category-search" placeholder="Filter this area" aria-label="Filter this area" /></label></div><div id="category-entity-grid" class="entity-grid">${entities.map((entity) => entityCard(entity)).join("")}</div></section>`); }
function groupedResults(results) { const used = new Set(); const groups = []; for (const category of ["people", "communities", "events", "opportunities", "entrepreneurship", "student_built"]) { const items = results.filter((entity) => !used.has(entity.id) && entity.domains?.includes(category)).slice(0, 3); items.forEach((item) => used.add(item.id)); if (items.length) groups.push({ category, items }); } return groups.map((group) => `<section class="answer-group"><div class="answer-group__heading"><span class="section-kicker">${categories[group.category].label}</span><span>${group.items.length} ${group.items.length === 1 ? "match" : "matches"}</span></div><div class="entity-grid entity-grid--answer">${group.items.map((entity) => entityCard(entity, { compact: true })).join("")}</div></section>`).join(""); }
function askView(query) { const search = searchEntities(query); const intent = search.intent; const results = intent.discovery && !search.results.length ? discoverEntities().map((item) => item.entity) : search.results; const journey = buildJourney(query); rememberQuery(query); const strong = results.length >= 1; const lead = intent.discovery ? "Here are a few useful surprises from the Cornell ecosystem." : intent.category ? `I found ${results.length} ways into ${categories[intent.category].label.toLowerCase()} and connected areas.` : `I found ${results.length} resources that may help you start exploring.`; return appShell(`<section class="page-width ask-page"><div class="ask-page__header"><span class="section-kicker">Ask Student OS</span><h1>${strong ? "A place to start." : "Let's widen the map."}</h1><p>${strong ? lead : "I couldn't find a strong match in the Cornell resources currently indexed."}</p>${askBar(query)}</div>${strong ? `<div class="answer-summary"><span class="answer-summary__mark">✦</span><p>${escapeHtml(query)}</p><span class="answer-summary__hint">${journey ? "Journey mode" : intent.discovery ? "Discovery mode" : "Connected results"}</span></div>${journey ? journeyView(journey) : ""}<div class="answer-groups">${groupedResults(results)}</div>` : `<div class="empty-search"><span>⌕</span><h2>Try a direction instead.</h2><p>Explore a category or ask about entrepreneurship, AI, communities, events, research, or student-built tools.</p><div class="empty-links">${Object.keys(categories).map((category) => `<button data-route="category/${category}">${categories[category].label} ↗</button>`).join("")}</div></div>`}</section>`); }
function relatedSections(entityId) { const related = getRelatedEntities(entityId); return ["people", "communities", "events", "opportunities", "entrepreneurship", "student_built"].map((category) => ({ category, items: related.filter((entity) => entity.domains?.includes(category)) })).filter((group) => group.items.length).map((group) => `<section class="related-section"><div class="related-section__heading"><span class="section-kicker">${categories[group.category].label}</span><span>${group.items.length}</span></div>${group.items.map((item) => `<button class="related-row" data-entity-id="${escapeHtml(item.id)}"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(getRelationshipLabel(entityId, item.id))} · ${escapeHtml(sourceLabel(item.source.sourceType))}</small></span><span>↗</span></button>`).join("")}</section>`).join(""); }
function detailView(id) { const entity = getEntityById(id); if (!entity) return homeView(); rememberEntity(id); const primaryLink = entity.links?.find((link) => link.isPrimary) || entity.links?.[0]; const category = entity.domains?.find((domain) => categories[domain]); const continueJourney = buildJourney(`${entity.name} ${(entity.tags || []).join(" ")}`); return appShell(`<section class="page-width detail-page"><button class="back-link" data-route="${category ? `category/${category}` : "home"}">← Back to ${category ? categories[category].label : "home"}</button><div class="detail-layout"><article class="detail-content"><div class="detail-heading"><span class="entity-icon entity-icon--large">${iconForEntity(entity)}</span><div><div class="entity-card__topline"><span class="eyebrow">${escapeHtml(slugLabel(entity.kind))}</span><span class="source-badge source-badge--${escapeHtml(entity.source.sourceType)}">${escapeHtml(sourceLabel(entity.source.sourceType))}</span></div><h1>${escapeHtml(entity.name)}</h1></div></div><p class="detail-description">${escapeHtml(entity.shortDescription)}</p><div class="detail-tags">${(entity.tags || []).map((tag) => `<span class="tag">${escapeHtml(tag.replaceAll("-", " "))}</span>`).join("")}</div>${entity.audience ? `<div class="detail-block"><span class="section-kicker">Good to know</span><p>${escapeHtml([...(entity.audience.audiences || []), ...(entity.audience.programs || [])].join(" · "))}</p></div>` : ""}<div class="detail-block detail-source"><span class="section-kicker">Source</span><p>${escapeHtml(entity.source.sourceName)}${entity.lastVerifiedAt ? ` · verified ${escapeHtml(entity.lastVerifiedAt)}` : ""}</p></div><div class="detail-actions"><a class="primary-action" href="${escapeHtml(primaryLink?.url || entity.source.sourceUrl)}" target="_blank" rel="noreferrer">Open original resource <span>↗</span></a><button class="save-action ${isSaved(id) ? "save-action--saved" : ""}" data-save-id="${escapeHtml(id)}">${isSaved(id) ? "Saved" : "Save for later"} <span>＋</span></button></div></article><aside class="detail-aside"><div class="aside-note"><span class="aside-note__mark">✦</span><p>Student OS is a discovery layer. When you're ready to act, we take you to the original resource.</p></div><div class="related-panel"><div class="section-kicker">Connected ecosystem</div><h2>Related</h2>${relatedSections(id) || `<p class="muted">Explore a little more and we'll keep building the map.</p>`}</div></aside></div>${continueJourney ? journeyView(continueJourney, true) : ""}</section>`); }

function savedView() { const saved = savedEntities(); const groups = Object.keys(categories).map((category) => ({ category, items: saved.filter((entity) => entity.domains?.[0] === category) })).filter((group) => group.items.length); return appShell(`<section class="page-width saved-page"><span class="section-kicker">Your workspace</span><h1>My Saved</h1><p>Keep the Cornell resources you want to come back to.</p>${groups.length ? groups.map((group) => `<section class="saved-group"><div class="section-heading"><div><span class="section-kicker">${categories[group.category].label}</span><h2>${group.items.length} saved</h2></div></div><div class="entity-grid">${group.items.map((entity) => entityCard(entity)).join("")}</div></section>`).join("") : `<div class="empty-search saved-empty"><span>☆</span><h2>Save anything you want to come back to.</h2><p>Your saved resources will appear here, organized by the areas they connect to.</p></div>`}</section>`); }
function profileView() { const profile = getProfile(); return appShell(`<section class="page-width profile-page"><span class="section-kicker">Your context</span><h1>Make Student OS yours.</h1><p>Keep this lightweight. Your context stays in this browser and only shapes local discovery.</p><form id="profile-form" class="profile-form"><div class="profile-form__section"><span class="section-kicker">Interests</span><div class="interest-grid">${interestOptions.map(([value, label]) => `<label class="interest-option"><input type="checkbox" name="interest" value="${value}" ${profile.interests?.includes(value) ? "checked" : ""} /><span>${label}</span></label>`).join("")}</div></div><div class="profile-fields"><label>School<select name="school"><option value="">Skip for now</option><option value="Johnson School of Management" ${profile.school === "Johnson School of Management" ? "selected" : ""}>Johnson School of Management</option></select></label><label>Program<select name="program"><option value="">Skip for now</option><option value="MBA" ${profile.program === "MBA" ? "selected" : ""}>MBA</option></select></label><label>Year<select name="year"><option value="">Skip for now</option><option value="Year 1" ${profile.year === "Year 1" ? "selected" : ""}>Year 1</option><option value="Year 2" ${profile.year === "Year 2" ? "selected" : ""}>Year 2</option></select></label></div><button class="primary-action" type="submit">Save context <span>↗</span></button></form><div class="settings-actions"><button class="text-action" data-clear-history>Clear exploration history</button><button class="text-action" data-clear-saved>Clear saved items</button><button class="text-action text-action--danger" data-reset-profile>Reset personalization</button></div></section>`); }
function render() { const { page, value } = state.route; document.querySelector("#app").innerHTML = page === "category" ? exploreView(value) : page === "entity" ? detailView(value) : page === "ask" ? askView(value || "") : page === "discover" ? discoverView() : page === "saved" ? savedView() : page === "profile" ? profileView() : page === "explore" ? exploreView() : homeView(); bindEvents(); }
function discoverView() { const items = discoverEntities(); return appShell(`<section class="page-width page-intro discover-page"><span class="section-kicker section-kicker--spark">Discovery layer</span><h1>✨ You might not know these exist.</h1><p>${items.length ? "Connected possibilities, selected from the trail you're making." : "Explore a few areas first and we'll start finding things for you."}</p><div class="entity-grid entity-grid--four">${items.map((item) => `<div class="discovery-item">${entityCard(item.entity)}<div class="discovery-reason">${escapeHtml(discoveryReason(item))}</div></div>`).join("")}</div></section>`); }
function navigate(path) { const [page, rawValue] = path.split("/"); state.route = { page: page || "home", value: rawValue ? decodeURIComponent(rawValue) : undefined }; history.pushState({}, "", `#${path}`); window.scrollTo({ top: 0, behavior: "smooth" }); render(); }
function bindEvents() {
  document.querySelectorAll("[data-route]").forEach((element) => element.addEventListener("click", () => navigate(element.dataset.route)));
  document.querySelectorAll("[data-category]").forEach((element) => element.addEventListener("click", () => { rememberCategory(element.dataset.category); navigate(`category/${element.dataset.category}`); }));
  document.querySelectorAll("[data-ask-query]").forEach((element) => element.addEventListener("click", () => navigate(`ask/${encodeURIComponent(element.dataset.askQuery)}`)));
  document.querySelectorAll("[data-entity-id]").forEach((element) => { const open = () => navigate(`entity/${element.dataset.entityId}`); element.addEventListener("click", open); element.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open(); } }); });
  document.querySelectorAll("[data-save-id]").forEach((element) => element.addEventListener("click", (event) => { event.stopPropagation(); toggleSaved(element.dataset.saveId); render(); }));
  document.querySelectorAll("[data-save-journey]").forEach((element) => element.addEventListener("click", (event) => { event.stopPropagation(); element.dataset.saveJourney.split(",").filter(Boolean).forEach((id) => { if (!isSaved(id)) toggleSaved(id); }); render(); }));
  const askForm = document.querySelector("#ask-form"); if (askForm) askForm.addEventListener("submit", (event) => { event.preventDefault(); const query = document.querySelector("#ask-input")?.value.trim(); if (query) navigate(`ask/${encodeURIComponent(query)}`); });
  const search = document.querySelector("#category-search"); if (search) search.addEventListener("input", () => { const category = state.route.value; const query = normalize(search.value); const filtered = getEntitiesByCategory(category).filter((entity) => entitySearchText(entity).includes(query)); document.querySelector("#category-entity-grid").innerHTML = filtered.length ? filtered.map((entity) => entityCard(entity)).join("") : `<div class="empty-state"><span>⌕</span><h3>No matches yet</h3><p>Try a broader word or explore another area.</p></div>`; bindEvents(); });
  document.querySelectorAll("[data-skip-onboarding]").forEach((element) => element.addEventListener("click", () => { updateMemory({ onboardingComplete: true }); render(); }));
  const onboarding = document.querySelector("#onboarding-form"); if (onboarding) onboarding.addEventListener("submit", (event) => { event.preventDefault(); saveProfileForm(onboarding); updateMemory({ onboardingComplete: true }); render(); });
  const profileForm = document.querySelector("#profile-form"); if (profileForm) profileForm.addEventListener("submit", (event) => { event.preventDefault(); saveProfileForm(profileForm); navigate("home"); });
  document.querySelectorAll("[data-clear-history]").forEach((element) => element.addEventListener("click", () => { const current = memory(); updateMemory({ viewedEntityIds: [], viewedEntities: [], selectedCategories: [], recentQueries: [] }); render(); }));
  document.querySelectorAll("[data-clear-saved]").forEach((element) => element.addEventListener("click", () => { updateMemory({ savedEntityIds: [] }); render(); }));
  document.querySelectorAll("[data-reset-profile]").forEach((element) => element.addEventListener("click", () => { localStorage.removeItem("student-os-memory"); render(); }));
}
function saveProfileForm(form) { const interests = [...form.querySelectorAll('input[name="interest"]:checked')].map((input) => input.value); const data = new FormData(form); updateMemory({ profile: { university: "Cornell University", school: data.get("school") || "", program: data.get("program") || "", year: data.get("year") || "", interests } }); }
async function init() { try { const [entitiesResponse, relationshipsResponse] = await Promise.all([fetch(`${DATA_ROOT}/entities.json`), fetch(`${DATA_ROOT}/relationships.json`)]); state.entities = await entitiesResponse.json(); state.relationships = await relationshipsResponse.json(); const hash = window.location.hash.replace(/^#/, "") || "home"; const [page, rawValue] = hash.split("/"); state.route = { page, value: rawValue ? decodeURIComponent(rawValue) : undefined }; render(); } catch (error) { document.querySelector("#app").innerHTML = `<div class="load-error"><h1>Student OS is taking a moment.</h1><p>We couldn't load the Cornell resource dataset.</p><code>${escapeHtml(error.message)}</code></div>`; } }
window.addEventListener("popstate", init); init();
